nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &
nohup python -u consumer.py >/dev/null 2>&1 &